---
- hosts: 172.31.81.137
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: i want create a static file
    copy:
     src: mystatic
     dest: /home/ubuntu/staticfile

  - name: i want install web server
    apt:
     name: apache2
     state: present
  - name: i want create dynamic files
    template:
     src: myindex.j2
     dest: /var/www/html/index.html
    notify: restartwebserver

  handlers:
  - name: restartwebserver
    service:
     name: apache2
     state: restarted
    