---
- hosts: all
  become: yes
  tasks:
  - name: i want install webserver
    apt:
     name: apache2
     state: present

  - name: i want start web server
    service:
     name: apache2
     state: started